spring:
  application:
    name: servicio-zuul-server
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
zuul:
  routes:
   store:
    service-id: service-store
    path: /api/store/** 
   celulares:
    service-id: service-celulares
    path: /api/phone/**
   users:
    service-id: service-usuarios
    path: /api/us/**
   oauth:
    service-id: servicio-oauth
    path: /api/security/**
    sensitive-headers: Cookie,Set-Cookie

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation: 
          timeoutInMilliseconds: 20000